openapi: 3.0.0
info:
  version: 1.0.0
  title: ZigPRO
  description: "## Authentication\r\n\r\nAPI request to ZigPRO API is required to include bellow fields in the header:\r\n- **x-merchant-id: {merchant identifier}**\r\n- **x-api-key: {merchant API key}**\r\n\r\nMerchant should be able to obtain above credential information in ZigPro Portal.\r\n\r\nMerchant API key management:\r\n- Merchant generates API Key through ZigPro Portal.\r\n- ZigPro only stores hash value of API key in the database.\r\n- API key value is displayed in the Portal UI only once after generation. Merchant to copy and store the key safely.\r\n- Only one active API key is allowed at once. Whenever the merchant generate new API key, the existing key will be deactivate in 24 hours.\r\n\r\n**Signature verification**\r\n\r\nMerchant is also required to generate signature by merchant private key and include bellow fields in the header:\r\n- **x-signature: {signature}**\r\n\r\n**Signature generation steps**\r\n\r\n1. Build the signature payload:\r\n\r\n> POST method:\r\n> payload=(JSON string (request body)) + headers[merchant_id] + headers[request_id] + headers[request_date_time]\r\n\r\n> GET method:\r\n> payload=headers[merchant_id] + headers[request_id] + headers[request_date_time]\r\n\r\n2. Encode the payload with UTF-8\r\n\r\n3. Sign the encoded payload by merchant private key\r\n\r\n> Algorithm: SHA256withRSA\r\n\r\n4. Base64 encode the signed value\r\n\r\n> signature=Base64Encode(signed_value)\r\n\r\nMerchant key management:\r\n- Merchant upload and manage their public key through ZigPro Portal\r\n- Only one active public key at a time\r\n- When merchant replace the current public key with their new ones, the old key is still active for 24 hours before becoming permanent invalid."
  contact:
    name: Herman Santoso
    url: www.zig.live
    email: hermans@comfortdelgro.com
  license:
    url: www.zig.live
    name: Open
servers:
  - url: 'https://paymentorchestrator-zigpro-sit.zig.live'
    description: Staging Environment
  - url: 'https://paymentorchestrator-zigpro-sit.zig.live'
    description: Production Environment
paths:
  /v1/register:
    post:
      tags:
        - Register Payment Method
      summary: Register Payment Method
      description: Register Payment Method API is used to obtain token from PSP for subsequent payment operations
      operationId: post-v1-register
      parameters:
        - name: x-merchant-id
          in: header
          description: Merchant Identifier
          required: true
          schema:
            type: string
        - name: x-api-key
          in: header
          description: Merchant API Key
          required: true
          schema:
            type: string
        - name: x-signature
          in: header
          description: Signature
          required: true
          schema:
            type: string
        - name: x-idempotency-key
          in: header
          description: Idempotency Key
          schema:
            type: string
        - name: x-request-timestamp
          in: header
          description: Request Timestamp
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                merchant_txn_id:
                  type: string
                routing_code:
                  type: string
                payer:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    mobile_no:
                      type: string
                    email:
                      type: string
                    address_1:
                      type: string
                    address_2:
                      type: string
                    state:
                      type: string
                    city:
                      type: string
                    country:
                      type: string
                    postal_code:
                      type: string
                  required:
                    - id
                    - name
                    - mobile_no
                    - email
                device_info:
                  type: object
                  properties:
                    type:
                      type: string
                    udid:
                      type: string
                    ip:
                      type: string
                payment_method:
                  type: string
                payment_info:
                  type: object
                  properties:
                    card_number:
                      type: string
                    holder_name:
                      type: string
                    exp_month:
                      type: string
                    exp_year:
                      type: string
                    cvv:
                      type: string
                    card_type:
                      type: string
                    complete_3ds_mode:
                      type: string
                return_url:
                  type: string
                metadata:
                  type: object
              required:
                - merchant_txn_id
                - payer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  payment_ref:
                    type: string
                  merchant_txn_id:
                    type: string
                  response_code:
                    type: string
                  message:
                    type: string
                  action:
                    type: object
                    properties:
                      method:
                        type: string
                      payment_data:
                        type: string
                      type:
                        type: string
                      payment_method_type:
                        type: string
                      url:
                        type: string
                  payment_token:
                    type: string
                  token_provider:
                    type: string
                  payment_detail:
                    type: object
                    properties:
                      bin_no:
                        type: string
                      trailing_no:
                        type: string
                      exp_month:
                        type: string
                      exp_year:
                        type: string
                      card_type:
                        type: string
          headers:
            x-response-timestamp:
              schema:
                type: string
      servers:
        - url: 'https://paymentorchestrator-zigpro-sit.zig.live'
          description: Staging Environment
        - url: 'https://paymentorchestrator-zigpro-sit.zig.live'
          description: Production Environment
tags:
  - name: Authentication
    description: Authentication requirement to consume ZogPRO API
  - name: Register Payment Method
    description: Register Payment Method
components:
  securitySchemes:
    x-api-key:
      type: apiKey
      name: x-api-key
      in: header
x-internal: false
